require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'



target 'MyApartment' do
  pod 'react-native-maps', :path => '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => '../node_modules/react-native-maps'
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'MyApartmentTests' do
    inherit! :complete
    # Pods for testing
  end

  
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({'Flipper' => '0.92.0', 'Flipper-Folly' => '2.6.7'})
  #use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'MyApartment-tvOS' do
  # Pods for MyApartment-tvOS

  target 'MyApartment-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
